version: "3.7"

volumes:
  diskyvideo:
    driver_opts:
      type: nfs
      o: "addr=192.168.0.20,nfsvers=4,ro"
      device: ":/volume1/video"

services:
  # app_proxy:
  #   environment:
  #     APP_HOST: bb-ate-jellyfin_server_1
  #     APP_PORT: 8096
  #     PROXY_AUTH_ADD: "false"

  server:
    image: jellyfin/jellyfin:10.10.4
    restart: on-failure
    hostname: "${DEVICE_HOSTNAME}"
    network_mode: 'host'
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
      - diskyvideo:/media