version: "3.7"

services:
  server:
    image: ghcr.io/tasmoadmin/tasmoadmin:v4.2.3
    restart: on-failure
    ports:
      - 8080:80
    hostname: "${DEVICE_HOSTNAME}"
    volumes:
      - ${APP_DATA_DIR}/data:/data