version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: bb-ate-tasmoadmin_server_1
      APP_PORT: 8080
    
  server:
    image: ghcr.io/tasmoadmin/tasmoadmin:v4.2.3
    restart: on-failure
    hostname: "${DEVICE_HOSTNAME}"
    volumes:
      - ${APP_DATA_DIR}/data:/data